language: rust

matrix:
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

    - rust: stable
      os: osx
      env: TARGET=x86_64-apple-darwin

cache:
  timeout: 360
  cargo: true

before_cache:
  - chmod -R a+r $HOME/.cargo

env:
  global:
    - CRATE_NAME=mdbook

script:
  - cargo test --all
  - cargo test --all --no-default-features

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: hgJFxKEYRmNpvjcLANPU2MqQ+bCAS2kSJs3ayf5xAjVgUoTGUFr8Zu+xErp02k0qq06rtA1VaI6HOirdQwgQqlrvZwXy3Nib8kdldsGtxLUcxpHn2u4C+DPKz++1J3/25IPk+IwGpTHEGtdihy+6VoVhj6/mASNTETX5W1xIF8ppCHoFPFrlzdTDyAZxIsX1pGeSOVsLCs1s87lOHMltVKyiqZkSmff3dtef5gyA9b9Osmez75Ek4PPEEIzCaTA3vvFrEaPaYH2ctXo1UH3D4myVJ6TlNSmQjW3GTLhPXxBP5AI+5SdvN20YS0Wa0SLMiIbde+Gl4JkkcA3eS7zbs9Nrb1+wCj5UirVOvU2LTa/NmASWGahzbgo/wBUkJ4sj1PIwMP2zLRM9GZMwPNrKSRy4sPAffQLdszh1JrfWediiTBzH2T5MDO8CgbrMZP2+bcwxIqy5BLtnwxYe5tYf6G4LRyu8kc2rHQoAWzqrJWQfO+Myr3F/v1FL6q75YhFTaHoTO+1jU/g4QkI3RTYI/qBULrONYmNZdjjwUtV4mPGZPUY7KwDWa7fqz2c1a9drpRSudztIKtUTTBaISbWWbt/i6VbejUVT3UPXLZzduXQ/NQx5U5RQeXunZ9LepGShJtQs7eoWlHQyLDfqmXAJQhUnPFflHxwt9k8+Mc9Q83E=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  skip_cleanup: true
  all_branches: true

# branches:
#   only:
#     - master
#     - /^v\d+\.\d+\.\d+.*$/

# notifications:
#   email:
#     on_success: never
