language: rust

matrix:
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

    - rust: stable
      os: osx
      env: TARGET=x86_64-apple-darwin

cache:
  timeout: 360
  cargo: true

before_cache:
  - chmod -R a+r $HOME/.cargo

env:
  global:
    # GITHUB_TOKEN — This is the encrypted OAuth token for deployment.
    - secure: yrjJkSu9JrosCBb3CjISL4sMdGpyEXL/o9JqslaJVlyLsvtAB2/NyAlnivbVfwMNctaVZM8n82J7Vjpi/2UOGsXGCoLI4Au6YWdH2Y/z3tre+P5r2NyDE/GfZ39hSklTaVLyzNn4KbXrBCe/FAkjhLlzyvSYV8k57GS4+TDhokE/BcO+CbRr3Hm+rcphLsd/wJ+OcdiCRQ4iIRPfLpit36N2/YI4s+NxFPlDsVGXezYWMYKPRaK6Ef04NHM/2fcHNp19+nhGRbCus+mn474c62IVwpt7NsK48hRQbMtbYXT/w5uap0uAvJ/xr2kLRoUR/3P7SgWqip+hG5ZkdVP6dGVOml08Ow/8Y1VLLy13Wb7c18jcaDrQ1OWD6eGgIEvi8WTFEcLbsWeacZZVX2MDj4JLoA6T+RevAwdHMDu34pGar9WJBA3DL0XT3kGPbhQGEq8uGuVBoAD/U4Za594oB/633Te/fR/RRjMx9AcBBn7W+50XrBfVJhOkVIxfIcdf93gxmg8x45Tyfk7+JxyOEv4qvSUBRjgO6aTqN1VtTqnfEgUO2ulgNG/6IaD55Lxn2jahCAKt5Ab83sWNfdblS+tUqPNrupy4njPINPmG6hMtwYQc3H64pNcfGidSmfsljYH8BB8yoM0Q8Ja6GfijcQuLOMXN/AzTQ3z8SYmkNUo=
    - CRATE_NAME=mdbook

script:
  - cargo test --all
  - cargo test --all --no-default-features

before_deploy:
  - cargo run -- build book-example
  - sh ci/before_deploy.sh

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
    on:
      condition: "$TRAVIS_RUST_VERSION = stable"
      tags: true
    skip_cleanup: true
  - provider: pages
    local_dir: book-example/book
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    on:
      branch: master

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never
